name: Integration With Docker
on: 
  push:
    branches:
      - main
jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from github
      uses: actions/checkout@v3
    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME2 }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN2 }}
    
    - name: Build and push to Docker hub
      uses: docker/build-push-action@v3 
      with:
        context: .
        push: true 
        tags: veisprocure2/jsxboard:latest, veisprocure/jsxboard:${{ github.run_number }}