export const famill1_options_pr = [
    {label: " "},
    {label: "ACESSORIO INST.ELET. | AHELIA"},
    {label: "ARMAZENAGEM  FLUIDOS | ASFLST"},
    {label: "AUTOMAÇÃO E INSTRUM. | AOAUIN"},
    {label: "CABOS | AACABL"},
    {label: "CAMINHOS DE CABOS | ABCBTR"},
    {label: "COMPON. ELETRÓNICOS | AUELCO"},
    {label: "COMÉRCIO | DBTRAD"},
    {label: "CONSUMÍVEIS | BFMEAN"},
    {label: "DATACENTER & CLOUD | DATACC"},
    {label: "DISTR. REGUL. FLUIDO | ARDIFL"},
    {label: "DISTRIBUIÇÃO DE ENERGIA | AFENDI"},
    {label: "ENVOLUCRO / ARMÁRIO | AIENEQ"},
    {label: "EPI E VESTUÁRIO | BEEPVP"},
    {label: "EQUIP. DE AVAC | ATTEQF"},
    {label: "EQUIP. DE ESTALEIRO | AXEQSI"},
    {label: "EQUIP. MECÂNICOS | AVMEMA"},
    {label: "EQUIP. REDES INFORM | ANEQTE"},
    {label: "EQUIP. TESTE | AWNDCO"},
    {label: "FERRAMENTAS | BCTOOL"},
    {label: "FORNEC. DE ENERGIA | BOENSU"},
    {label: "GESTÃO DE EDIFÍCIOS | AJBUMA"},
    {label: "GESTÃO DE SERVIÇOS | BNFAMT"},
    {label: "ILUMINAÇÃO | ADLGTG"},
    {label: "INFORMÁTICA | BGINFO"},
    {label: "MANUT. EQUIPAMENTOS | BLMAEQ"},
    {label: "MAT. DE CONSTRUÇÃO | BAMACO"},
    {label: "MATÉRIA-PRIMA | BBRAMA"},
    {label: "OUTSOURCING SERVIÇOS | BNFAMA"},
    {label: "PREST. DE SERVIÇOS | BMSERV"},
    {label: "PRODUÇÃO DE ENERGIA | AEENPR"},
    {label: "PRODUÇÃO DE FLUIDOS | APFLPR"},
    {label: "QUINQUILHARIA | BDHWRE"},
    {label: "REDES DE TELECOMUNIC | AMTENW"},
    {label: "SEGURANÇA | ALSAEP"},
    {label: "SINALIZ. RODOVIARIA | AZROSS"},
    {label: "SOM  E  VÍDEO | AKSOVI"},
    {label: "SUBCONT. ENGENHARIA | BHSCST"},
    {label: "SUBCONT. INDUSTRIAL | BKSCID"},
    {label: "SUBCONT. INTERNA | BJSCIN"},
    {label: "SUBCONT. OBRA | BISCSI"},
    {label: "SUPORTES | ACBRKT"},
    {label: "TRABALHO TEMPORÁRIO | BPTELA"},
    {label: "TRANSPORTE DE ENERGIA | AGENTR"},
    {label: "TRATAMENTO DE FLUIDOS | AQFLTR"},
    {label: "VEÍCULOS | AYVEEN"}
    ]